<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRateRepository extends EntityRepository
{

//
//    public function getRecentCurrencyRates()
//    {
//
//        $lastestDate = $this->_em->createQueryBuilder()
//                        ->addSelect('MAX(cr.createdAt)as lastest')
//                        ->from('AppBundle:CurrencyRate', 'cr')
//                        ->getQuery()->getResult()
//
//        ;
//        return $result = $this->_em->createQueryBuilder()
//                ->addSelect('c.currencyCode,c.reverseRate')
//                ->from('AppBundle:CurrencyRate', 'c')
//                ->where("c.createdAt = :lastestDate")
//                ->setParameter('lastestDate', $lastestDate)
//                ->getQuery()
//                ->getResult()
//        ;
//    }

    public function getLastest()
    {
        return $result = $this->_em->createQueryBuilder()
                ->addSelect('c.updatedAt')
                ->from('AppBundle:CurrencyRate', 'c')
                ->orderBy('c.updatedAt', 'DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getResult()
        ;
    }

    public function getAvailableCurrencyRateCodes()
    {
        return $result = $this->_em->createQueryBuilder()
                ->addSelect('DISTINCT c.currencyCode')
                ->from('AppBundle:CurrencyRate', 'c')
                ->getQuery()
                ->getResult()
        ;
    }

}
