<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRateHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRateHistoryRepository extends EntityRepository
{

    public function getCurrencyRateHistory($currentPage = 1, $limit = 20)
    {
        // Create our query
        $query = $this->createQueryBuilder('c')
                ->orderBy('c.createdAt', 'DESC')
                ->getQuery();

        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }

    public function paginate($dql, $page, $limit)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1)) // Offset
                ->setMaxResults($limit); // Limit

        return $paginator;
    }

    public function getCurrencyRateHistoryLike($q,$currentPage = 1, $limit = 20)
    {

        $query = $this->createQueryBuilder('c')
                        ->orWhere('c.createdAt LIKE :query')
                        ->orWhere('c.reverseRate LIKE :query')
                        ->orWhere('c.currencyCode LIKE :query')
                        ->orderBy('c.createdAt', 'DESC')
                        ->setParameter('query', "%$q%")
                        ->getQuery()
        ;


        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }
    
//    public function getCurrencyRateHistoryLike($q)
//    {
//        
//        return $this->createQueryBuilder('c')
//                ->orWhere('c.createdAt LIKE :query')
//                ->orWhere('c.reverseRate LIKE :query')
//                ->orWhere('c.currencyCode LIKE :query')
//                ->orderBy('c.createdAt', 'DESC')
//                ->setParameter('query',"%$q%")
//                ->getQuery()
//                ->getResult()
//                ;
//
//    }

}
