<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRateProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRateProviderRepository extends EntityRepository
{
}
