<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaxAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxAmountRepository extends EntityRepository
{

    public function findBySearchResult($formData)
    {

        $driver = $formData['driver_age'];
        $vehicleType = $formData['vehicle_type'];
        $engineCapacity = $formData['engine_capacity'];
        $region = $formData['region'];
        $others = $formData['others'];

        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();

        $result = $qb->select('t')
                ->from('TaxAmount', 't')
                ->where('t.tax= :tax')
                ->setParameter('tax', $region);

        dump($result);

        exit;
    }

}
