<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends EntityRepository
{

    public function findLike($q)
    {
        return $result = $this->createQueryBuilder('t')
                ->where('t.name LIKE :query')
                ->setParameter('query', "%$q%")
                ->getQuery()
                ->getResult()
        ;
    }

}
