basetax_index:
    path:     /
    defaults: { _controller: "AppBundle:BaseTax:index" }
    methods:  GET

basetax_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:BaseTax:show" }
    methods:  GET

basetax_new:
    path:     /new
    defaults: { _controller: "AppBundle:BaseTax:new" }
    methods:  [GET, POST]

basetax_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BaseTax:edit" }
    methods:  [GET, POST]

basetax_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BaseTax:delete" }
    methods:  DELETE
