policyhistory_index:
    path:     /
    defaults: { _controller: "AppBundle:PolicyHistory:index" }
    methods:  GET

policyhistory_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PolicyHistory:show" }
    methods:  GET

policyhistory_new:
    path:     /new
    defaults: { _controller: "AppBundle:PolicyHistory:new" }
    methods:  [GET, POST]

policyhistory_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:PolicyHistory:edit" }
    methods:  [GET, POST]

policyhistory_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:PolicyHistory:delete" }
    methods:  DELETE
