dashboard_taxes_index:
    path:     /
    defaults: { _controller: "AppBundle:Tax:index" }
    methods:  GET

dashboard_taxes_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Tax:show" }
    methods:  GET

dashboard_taxes_new:
    path:     /new
    defaults: { _controller: "AppBundle:Tax:new" }
    methods:  [GET, POST]

dashboard_taxes_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Tax:edit" }
    methods:  [GET, POST]

dashboard_taxes_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Tax:delete" }
    methods:  DELETE
